#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

mkdir -p "$install_dir/Modules"

chown -R "$app:www-data" "$install_dir"

chmod -R 775 "$install_dir/storage"
chmod -R 775 "$install_dir/bootstrap/cache"
chmod -R 775 "$install_dir/Modules"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 700 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Configuring $app..."

pushd "$install_dir"
	"php$php_version" artisan key:generate --no-interaction --force
	"php$php_version" artisan view:clear
	"php$php_version" artisan cache:clear
	"php$php_version" artisan optimize --no-interaction
	"php$php_version" artisan storage:link
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "$install_dir/storage/logs/laravel.log"
chmod -R 775 "$install_dir/storage/logs"

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="/var/log/nginx/$domain-access.log" --failregex="<HOST> .* \"(GET|POST) (/api/|/login).*\" (401|422)"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
