#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env storage Modules"

chown -R "$app:www-data" "$install_dir"

chmod -R 775 "$install_dir/storage"
chmod -R 775 "$install_dir/bootstrap/cache"

pushd "$install_dir"
	"php$php_version" artisan view:clear
	"php$php_version" artisan cache:clear
    "php$php_version" artisan optimize --no-interaction --verbose 2>&1
	"php$php_version" artisan storage:link
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

ynh_config_add_logrotate "$install_dir/storage/logs/laravel.log"

ynh_config_add_fail2ban --logpath="/var/log/nginx/$domain-access.log" --failregex="<HOST> .* \"(GET|POST) (/api/|/login).*\" (401|422)"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
